flowchart TD
cloned_files_TrickIT_frontend_src_components_Dashboard.js_loadPosts["<b>loadPosts</b><br/><small>(—)</small><br/><small>cloned_files\TrickIT\frontend\src\components\Dashboard.js</small><br/><small>[arrow_function]</small>"]
cloned_files_TrickIT_frontend_src_components_Dashboard.js_handleCreatePost["<b>handleCreatePost</b><br/><small>(—)</small><br/><small>cloned_files\TrickIT\frontend\src\components\Dashboard.js</small><br/><small>[arrow_function]</small>"]
cloned_files_TrickIT_frontend_src_components_Dashboard.js_handleCreatePost --> cloned_files_TrickIT_frontend_src_components_Dashboard.js_loadPosts