flowchart TD
cloned_files_TrickIT_frontend_src_components_Dashboard.js_handleCreatePost["<b>handleCreatePost</b><br/><small>(—)</small><br/><small>cloned_files\TrickIT\frontend\src\components\Dashboard.js</small><br/><small>[arrow_function]</small>"]
cloned_files_TrickIT_frontend_src_components_Profile.js_handleImageChange["<b>handleImageChange</b><br/><small>(—)</small><br/><small>cloned_files\TrickIT\frontend\src\components\Profile.js</small><br/><small>[arrow_function]</small>"]
cloned_files_TrickIT_frontend_tailwind.config.js_tailwind.config["<b>tailwind.config</b><br/><small>(—)</small><br/><small>cloned_files\TrickIT\frontend\tailwind.config.js</small><br/><small>[module]</small>"]
cloned_files_TrickIT_frontend_src_components_Dashboard.js_loadPosts["<b>loadPosts</b><br/><small>(—)</small><br/><small>cloned_files\TrickIT\frontend\src\components\Dashboard.js</small><br/><small>[arrow_function]</small>"]
cloned_files_TrickIT_frontend_src_components_Dashboard.js_Dashboard["<b>Dashboard</b><br/><small>(—)</small><br/><small>cloned_files\TrickIT\frontend\src\components\Dashboard.js</small><br/><small>[arrow_function]</small>"]
cloned_files_TrickIT_frontend_src_components_Dashboard.js_loadProfile["<b>loadProfile</b><br/><small>(—)</small><br/><small>cloned_files\TrickIT\frontend\src\components\Dashboard.js</small><br/><small>[arrow_function]</small>"]
cloned_files_TrickIT_frontend_src_services_api.js_getImageUrl["<b>getImageUrl</b><br/><small>(—)</small><br/><small>cloned_files\TrickIT\frontend\src\services\api.js</small><br/><small>[arrow_function]</small>"]
cloned_files_TrickIT_frontend_src_components_Dashboard.js_handleLogout["<b>handleLogout</b><br/><small>(—)</small><br/><small>cloned_files\TrickIT\frontend\src\components\Dashboard.js</small><br/><small>[arrow_function]</small>"]
cloned_files_TrickIT_frontend_src_components_Dashboard.js_handleCreatePost --> cloned_files_TrickIT_frontend_src_components_Dashboard.js_loadPosts
cloned_files_TrickIT_frontend_src_components_Dashboard.js_Dashboard --> cloned_files_TrickIT_frontend_src_components_Dashboard.js_loadProfile
cloned_files_TrickIT_frontend_src_components_Dashboard.js_Dashboard --> cloned_files_TrickIT_frontend_src_components_Dashboard.js_loadPosts
cloned_files_TrickIT_frontend_src_components_Dashboard.js_Dashboard --> cloned_files_TrickIT_frontend_src_services_api.js_getImageUrl
cloned_files_TrickIT_frontend_src_components_Dashboard.js_Dashboard --> cloned_files_TrickIT_frontend_src_components_Dashboard.js_handleLogout